<a href="https://colab.research.google.com/github/Bakedpeddler100/mini_project/blob/main/_mini_project_sentimental_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
#Training data(Text)-->Pre-process it to make ML to understand it-->ML Model-->Provide it a new test data-->Prediction
#.py is open source having numerous libraries
#below is the csv file from the review data from kaggle
!wget "https://www.dropbox.com/s/c6lmwqz67kpdsiq/review_dataset.csv" #request to get the file through URL

--2020-10-11 06:50:51--  https://www.dropbox.com/s/c6lmwqz67kpdsiq/review_dataset.csv
Resolving www.dropbox.com (www.dropbox.com)... 162.125.1.1, 2620:100:6016:1::a27d:101
Connecting to www.dropbox.com (www.dropbox.com)|162.125.1.1|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: /s/raw/c6lmwqz67kpdsiq/review_dataset.csv [following]
--2020-10-11 06:50:52--  https://www.dropbox.com/s/raw/c6lmwqz67kpdsiq/review_dataset.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc6bac915ac1f84539eee5f1e665.dl.dropboxusercontent.com/cd/0/inline/BBDbqtsBEsRizV72vC9E-XsvsIXx2N9s84ixdF4369FpwxZJZ9_Dy9eOMUAZIrP1Gqsntex-zVA-_TGaCejQcXPrmyC7hnSty5aP1pDv5EcC7kB8_AoWBPrDmZnYIK2IOaM/file# [following]
--2020-10-11 06:50:55--  https://uc6bac915ac1f84539eee5f1e665.dl.dropboxusercontent.com/cd/0/inline/BBDbqtsBEsRizV72vC9E-XsvsIXx2N9s84ixdF4369FpwxZJZ9_Dy9eOMUAZIrP1Gqsntex-zVA-_TGaCejQcXPrmyC7hnSt

In [44]:
import pandas as pd 
import numpy as np
df = pd.read_csv("review_dataset.csv")
df #data_frame and the given dataset is labelled data i.e., pos neg reviews

review label
0      The Buddy Holly Story opens on a shot of a yel...   pos
1      ***SPOILERS*** Like some evil Tinkers-to-Evers...   neg
2      Ghost of Dragstrip Hollow is a typical 1950's ...   neg
3      Whatever you do, don't stop watching when you ...   pos
4      This is one of those movies you think that the...   neg
...                                                  ...   ...
19995  O boy, was this really bad.<br /><br />I saw t...   neg
19996  Larry Fessenden has been thrashed by most of t...   pos
19997  This may or may not be the worst movie that St...   neg
19998  I have no idea what these people were thinking...   neg
19999  "The Groove Tube" was initially shown on video...   pos

[20000 rows x 2 columns]

In [45]:
df.shape

(20000, 2)

In [46]:
df['label'] #[0:20] for starting 20 lables

0        pos
1        neg
2        neg
3        pos
4        neg
        ... 
19995    neg
19996    pos
19997    neg
19998    neg
19999    pos
Name: label, Length: 20000, dtype: object

In [47]:
df['review'] #[0] to get the first review

0        The Buddy Holly Story opens on a shot of a yel...
1        ***SPOILERS*** Like some evil Tinkers-to-Evers...
2        Ghost of Dragstrip Hollow is a typical 1950's ...
3        Whatever you do, don't stop watching when you ...
4        This is one of those movies you think that the...
                               ...                        
19995    O boy, was this really bad.<br /><br />I saw t...
19996    Larry Fessenden has been thrashed by most of t...
19997    This may or may not be the worst movie that St...
19998    I have no idea what these people were thinking...
19999    "The Groove Tube" was initially shown on video...
Name: review, Length: 20000, dtype: object

In [48]:
df['review'][0] #dataset need to be tidy

'The Buddy Holly Story opens on a shot of a yellow neon moon on the roof of a roller rink in 1956 Lubbock, Texas. As the credits start, the camera moves down from the moon to the parking lot, into the roller rink, past the concessions and across the rink to a small bandstand where a small band is doing their sound check. It\'s a tracking shot Welles and Scorcese would both appreciate. It cuts to Buddy Holly\'s bespectacled face peering down in rapt concentration as he grips the headphones and talks to a man putting this band on the radio. <br /><br />A young Gary Busey plays Buddy Holly and his performance is key. He has to somehow show the passion that Holly had for his music to make the film work. This is a rock and roll story without lines of coke chased with shots of heroin and a fifth of whiskey. This isn\'t about a man with several women to choose between in a sex scandalized, brood abandoned lusty tragedy. This is a film about a nice Texas boy who respected his parents and went 

In [49]:
df['review'][1]

'***SPOILERS*** Like some evil Tinkers-to-Evers-to-Chance double-play combination we have in "Omen IV" the evil seed of the deceased AntiChrist Damien Thorn come back. Terrorizing his parents his schoolmates his neighbors and finally the entire world as a she named Delia York, Asia Vieila. After being given to a "deserving" couple the Yorks Karen & Gene, Fay Grant & Michael Woods,by the Catholic Church\'s St. Francis orphanage.<br /><br />Little Delia didn\'t waste any time making her peasants felt by scratching her mom at a house party. Later Delia almost get killed by a runaway truck only to have herself saved by this "Devil Dog" named Ryder. Going to school Delia takes care of the local bully by getting the big guy to wet himself in front of all his classmates. Later when his father threatens the Yorks with a law suit she has his head sliced off in a self-induced traffic accident! Delia is someone that you never mess with if you know what\'s good for you.<br /><br />Meanwhile Dalia\

In [50]:
#to clean up the data, we are going to use <nltk> library
import re #regular expression library
import nltk #to filter out the given dataset
from nltk.corpus import stopwords #stopwords are the irrelevant words like with,the,etc
#corpus is a sub-package inside nltk

nltk.download('stopwords')

sw = stopwords.words('english') #natural language 
print(sw)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'bo

In [51]:
def clean_text(sample):
  sample = sample.lower()
  sample = sample.replace("<br /><br />","")
  sample = re.sub("[^a-z]+", " ", sample)
  sample = sample.split(" ")

  sample = [word for word in sample if word not in sw] #it will skip the stopwords and known as list-comprehension
 
  sample = " ".join(sample)
  
  return sample

In [52]:
clean_text(df['review'][1])

' spoilers like evil tinkers evers chance double play combination omen iv evil seed deceased antichrist damien thorn come back terrorizing parents schoolmates neighbors finally entire world named delia york asia vieila given deserving couple yorks karen gene fay grant michael woods catholic church st francis orphanage little delia waste time making peasants felt scratching mom house party later delia almost get killed runaway truck saved devil dog named ryder going school delia takes care local bully getting big guy wet front classmates later father threatens yorks law suit head sliced self induced traffic accident delia someone never mess know good meanwhile dalia dad gene becomes big man town thinks getting elected congress champion clean air green trees crowd instead letting smog concrete boys take neighborhood eye white house bratty strange daughter delia anything gene york sudden good fortune later jo ann hearen hired delia nanny truth comes strange evil powers jo new age type rea

In [53]:
df['review'] = df['review'].apply(clean_text) #easier without using for loop
df

review label
0      buddy holly story opens shot yellow neon moon ...   pos
1       spoilers like evil tinkers evers chance doubl...   neg
2      ghost dragstrip hollow typical teens turmoil m...   neg
3      whatever stop watching think movie hang around...   pos
4      one movies think makers would refuse release t...   neg
...                                                  ...   ...
19995  boy really bad saw videotape scenes soundtrack...   neg
19996  larry fessenden thrashed comments forum well w...   pos
19997  may may worst movie steve martin ever made cer...   neg
19998  idea people thinking made film plot limited ac...   neg
19999   groove tube initially shown video first video...   pos

[20000 rows x 2 columns]

In [54]:
#we converted the whole data into numbers, input is reviews and output is labels
# x-->input
# y--> output
x = df['review'].values
y = df['label'].values

#dividing the data into training and testing part and here ratio is poop:poop 
x_train = x[0:15000]      # taking data for training
x_test = x[15000:20000]   # for testing the data set

y_train = y[0:15000]
y_test = y[15000:20000]

In [55]:
y_train #computer can't understand this pos,neg.So, we need to convert it into binary form that is pos=1 and neg=0.

array(['pos', 'neg', 'neg', ..., 'pos', 'pos', 'pos'], dtype=object)

In [56]:
#another library to convert pos/neg into 1/0
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder() # creating an object to call the class<LabelEncoder>

#fit: learning the mapping pos:1, neg:0
le.fit(y_train)

LabelEncoder()

In [57]:
y_train = le.transform(y_train) #conversion
y_test =  le.transform(y_test)

In [58]:
y_train[0:10] #observe the converted training part

array([1, 0, 0, 1, 0, 0, 1, 0, 0, 1])

In [59]:
# Bag of Word model
# it convert sentences into numbers

from sklearn.feature_extraction.text import CountVectorizer
#create object for ease

cv = CountVectorizer(max_features = 10000)

In [60]:
cv.fit(x_train)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=10000, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [61]:
cv.transform(x_train)
#it says that there are 15k of rows and 61533 are number of features
# next step is to convert sparse matrix into dense matrix 

<15000x10000 sparse matrix of type '<class 'numpy.int64'>'
	with 1293191 stored elements in Compressed Sparse Row format>

In [62]:
x_train = cv.transform(x_train).toarray() 
#it's consuming lot's of space so we will set the features value in CountVectorizer function or we can remove .toarray() RAM won't exceed
#x_train is converted into numbers basically it's converted into 2-D matrix

In [63]:
x_train.shape

(15000, 10000)

In [64]:
x_test = cv.transform(x_test).toarray()

In [65]:
x_test.shape #now we can train our model

(5000, 10000)

# **Model Training**

In [66]:
from sklearn.naive_bayes import MultinomialNB 

mnb = MultinomialNB()

In [67]:
#training part
mnb.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [68]:
#predicting the model
mnb.predict(x_test)  #mnb: model

array([0, 0, 1, ..., 0, 0, 0])

In [69]:
#to check the accuracy of the model
mnb.score(x_test, y_test)

0.8416

# **Predict for one sentence**


In [82]:
my_review = "Me is too busy, but she helps other as well in their work."
my_review = clean_text(my_review) #cleaning the review

In [83]:
my_review = cv.transform([my_review]) 
#using countvectorizer we are converting words into numbers, same as we did for the above model
# we are passing our review that we wrote in the cv.transform([])   
# it says 1 row and 10k columns/features

In [84]:
mnb.predict(my_review)
# here 1 depicts that Me is so positive hooman =)

array([1])